import React from 'react';

interface ShowcaseSite {
  name: string;
  category: string;
  url: string;
}

const sites: ShowcaseSite[] = [
  { name: 'Urban Brew & Bite', category: 'Hospitality', url: 'https://athena-cms-factory.github.io/urban-brew-bite' },
  { name: 'Urban Soles', category: 'E-commerce', url: 'https://athena-cms-factory.github.io/urban-soles' },
  { name: 'Belgian Chocolate Shop', category: 'E-commerce', url: 'https://athena-cms-factory.github.io/chocolade-shop' },
  { name: 'Academy-1', category: 'Education', url: 'https://athena-cms-factory.github.io/academy-1' },
  { name: 'De Schaar', category: 'Beauty & Wellness', url: 'https://athena-cms-factory.github.io/de-schaar' },
  { name: 'KDC IT Advies', category: 'IT Consultancy', url: 'https://athena-cms-factory.github.io/kdc-it-advies' },
  { name: 'Athena Pro', category: 'B2B / SaaS', url: 'https://athena-cms-factory.github.io/athena-pro' },
  { name: 'Bakkerij de Graankorrel', category: 'Retail & Food', url: 'https://athena-cms-factory.github.io/bakkerij-de-graankorrel' },
  { name: 'Cloud Architects', category: 'IT / Tech', url: 'https://athena-cms-factory.github.io/cloud-architects' },
  { name: 'Gentse Dakwerken', category: 'Construction', url: 'https://athena-cms-factory.github.io/gentse-dakwerken' },
  { name: 'Lex & Justitia Advocaten', category: 'Legal Services', url: 'https://athena-cms-factory.github.io/lex-justitia' },
];

const AthenaShowcase: React.FC = () => {
  return (
    <section id="athena-showcase">
      <div className="container">
        <h2>Athena CMS Factory — Live Showcase</h2>
        <p>
          Every website below was generated by{' '}
          <a href="https://athena-cms-factory.github.io/athena-hub/" target="_blank" rel="noopener noreferrer">
            Athena CMS Factory
          </a>
          , the Google Sheets-driven website factory I built from scratch. All sites are live — click any of them to explore.
        </p>
        <div className="row g-3 row-cols-1 row-cols-md-3 row-cols-lg-4">
          {sites.map((site) => (
            <div className="col d-flex align-items-stretch" key={site.name}>
              <a
                href={site.url}
                className="card shadow-sm text-decoration-none w-100"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="card-body">
                  <h5 className="card-title">{site.name}</h5>
                  <p className="card-text text-muted mb-0">{site.category}</p>
                </div>
              </a>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default AthenaShowcase;
